story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

tugas/urls.py
from django.urls import path
from . import views

app_name = 'tugas'

urlpatterns = [
    path('', views.home, name='index'),
    path('about/', views.about, name='about'),
    path('status/', views.status, name='status'),
    path('library/', views.library, name='library'),
]

tugas/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Status(models.Model):
    text = models.TextField(u'Status:', max_length=300)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

tugas/forms.py
from django import forms
from .models import Status

##Create your forms here
class StatusForm(forms.ModelForm):

    class Meta:
        model = Status
        fields = ('text',)

tugas/views.py
from django.shortcuts import render,get_object_or_404
from .models import Status
from .forms import StatusForm

# Create your views here.
def home(request):
    return render(request, 'pages/home.html', {})

def status(request):
    status = Status.objects.all()
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            form = StatusForm()
    else:
        form = StatusForm()
    return render(request, 'pages/status.html', {'status': status, 'form':form})

def about(request):
    return render(request, 'pages/about.html', {})

def library(request):
    return render(request, 'pages/library.html', {})

tugas/templates/pages/about.html
{% extends 'pages/base.html' %}{% load static %}{%block page_content %}

<body id="body" class="dark-mode">
    <div class="padding-welcome">
    <div class="row text-center">
        <div class="col-12 p0">
            <h1>About Me</h1>
        </div>
    </div>
    </div>
    <div class="text-center">
        <h4>Nama</h4>
        <p>Nabila Ayu Dewanti</p><br>
        <h4>NPM</h4>
        <p>1806205312</p><br>
        <h4>Jurusan</h4>
        <p>Ilmu Komputer</p><br>
        <h4>Tempat Kuliah</h4>
        <p>Universitas Indonesia</p><br>
        <h4>Angkatan</h4>
        <p>2018</p><br>
        <h4>Hobi</h4>
        <p>Baca novel dan nonton TV series</p><br>
    </div>
    <div class="accordion-container">
      <h4>My Resume</h4>
      <div class="set">
        <a href="#">
          Aktivitas 
          <i class="fa fa-plus"></i>
        </a>
        <div class="content">
          <p>Pada saat ini, saya menjalani hari-hari sebagai mahasiswi Ilmu Komputer UI. Ditambah lagi, menjalani tanggungjawab sebagai PJ Kreatif BETIS 2020 dan staff BEM Fasilkom UI.</p>
        </div>
      </div>
      <div class="set">
        <a href="#">
          Organisasi/Kepanitiaan 
          <i class="fa fa-plus"></i>
        </a>
        <div class="content">
          <ul>
            <li><b>PIC of Creative</b><br>BETIS Fasilkom UI 2020</li>
            <li><b>Staff of Community Service Department</b><br>BEM Fasilkom UI</li>
            <li><b>Staff of Digital Marketing</b><br>COMPFEST</li>
            <li><b>Secretary II</b><br>Wisuda Genap Fasilkom UI 2019</li>
            <li><b>Staff of Event Division</b><br>BETIS Fasilkom UI 2019</li>
            <li><b>Staff of Design Division</b><br>9th OLIM UI</li>
          </ul>
        </div>
      </div>
      <div class="set">
        <a href="#">
          Prestasi
          <i class="fa fa-plus"></i>
        </a>
        <div class="content">
          <ul>
            <li><b>Top 10 Finalist, Technovation Arkavidia 5.0</b><br>Bandung Institute of Technology</li>
          </ul>
        </div>
      </div>
    </div>

<!-- external js -->
<script src="{% static 'js/myScript.js' %}"></script>
</body>
{% endblock %}

tugas/templates/pages/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <!-- Google jQuery CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <title>My Website</title>
</head>
<body id="body" class="dark-mode">
    <nav class="navbar navbar-expand-md bg-nav sticky-top">
        <div class="container-fluid">
        <a class="navbar-brand" id="text-portfolio" href="{% url 'tugas:index' %}">MY WEBSITE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            <a class="nav-link" id="text-portfolio" href="{% url 'tugas:about' %}">ABOUT</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" id="text-portfolio" href="{% url 'tugas:status' %}">STATUS</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" id="text-portfolio" href="{% url 'tugas:library' %}">LIBRARY</a>
            </li>
            <li class="nav-item">
            <button id="button-theme" type="button" name="dark_light" onclick="toggleDarkLight()" title="Ubah Tema">🌓</button>
            </li>
        </ul>
        </div>
        </div>
    </nav>
</body>
{% block page_content %} {% endblock %}
</html>

tugas/templates/pages/home.html
{% extends 'pages/base.html' %}{% load static %}{%block page_content %}

<body>
    {% if user.is_authenticated %}
        <div class="text-center middle">
        <h1 class="display-2">Hi {{ user.username }}!</h1>
        <a role="button" id="logoutButton" class="btn btn-primary" href="{% url 'logout' %}">logout</a>
        </div>
    {% else %}
        <div class="text-center middle">
        <h1 class="display-2">Welcome!</h1>
        <p>Oops! You are not logged in yet</p>
        <a role="button" id="loginButton" class="btn btn-primary" href="{% url 'login' %}">login</a>
        </div>
    {% endif %}

<!-- external js -->
<script src="{% static 'js/myScript.js' %}"></script>
</body>

{% endblock %}

tugas/templates/pages/library.html
{% extends 'pages/base.html' %}{% load static %}{%block page_content %}

<body>
    <div class="padding-welcome">
    <div class="row text-center">
        <div class="col-12 p0">
            <h1>My Library</h1>
        </div>
    </div>
    </div>
    <div class="text-center mb-30">
        <input id="search" placeholder="Title">
        <button id="button-booksearch" type="button">Search</button>
    </div>
    <div id="booktable" class="booktable text-center">
        <table class="table table-striped table-bordered table-hover">
            <thead class="text-center">
            <tr>
                <th>Image</th>
                <th>Title</th>
                <th>Author</th>
                <th>Publisher</th>
                <th>Preview</th>
            </tr>
            </thead>
            <tbody id="results">
            </tbody>
        </table>

    </div>

<!-- external js -->
<script src="{% static 'js/myScript.js' %}"></script>
</body>
{% endblock %}

tugas/templates/pages/status.html
{% extends 'pages/base.html' %}{% load static %}{%block page_content %}
<!doctype html>
<body id="body" class="dark-mode">
    <div class="padding-welcome">
    <div class="row text-center">
        <div class="col-12 p0">
            <h1>Halo, apa kabar?</h1>
        </div>
    </div>
    </div>
    {% block content %}
    <div class="text-center">
    {% for comment in status %}
        <div class="comment">
            <div class="date">{{ comment.created_date }}</div>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
    {% empty %}
        <p>No status here yet :(</p>
    {% endfor %}
    <form method="POST">
        {% csrf_token %}
        <table class="form">
        {{ form.as_table }}
        <tr><td colspan="2">
            <button type="submit" class="btn btn-primary btn-curve margin-top-1"><b>Add Status</b></button>
        </td></tr>
        </table> 
    </form>
    </div>
    {% endblock %}

<!-- external js -->
<script src="{% static 'js/myScript.js' %}"></script>
</body>
{% endblock %}